### ISSUE TITLE
Defect - 1 -  Title in about page not vertically centered

### ISSUE THREAD

**Issue by sidthesloth92** [shprink/trendingdevs.com#1]
The title in about page is not vertically centered. Refer screen shot.
<img width="348" alt="screen shot 2015-11-13 at 9 23 04 pm" src="https://cloud.githubusercontent.com/assets/4656109/11150196/c9fb1db4-8a4c-11e5-82be-7e6a51198abd.png">

**Comment by shprink** [comment]
:+1:  thanks for sharing

**Comment by shprink** [comment]
Done
