### ISSUE TITLE
grammar fixes

### ISSUE THREAD

**Issue by davidmoten** [shprink/trendingdevs.com#13]
cool site, thanks!

Here are some grammar fixes for the About page:

> This application aims to give developers the exposition they deserve

-> 

> This application aims to give developers the exposure they deserve

Another (in two places)

> also about hard working, sharing knowledge and keeping learning

-> 

> also about working hard, sharing knowledge and continuing to learn (keeping learning sounds quite weird)

Another

> The trending ranking rewards developers that have the most evolved within the week. 

->

> The trending ranking rewards developers that have evolved the most within the week. 

I have to admit that I don't know what you mean here by evolved, might need clarification.

**Comment by shprink** [comment]
> I have to admit that I don't know what you mean here by evolved, might need clarification.

I meant it rewards the developers which ranking has increase the most.

thanks for those changes, it will be released in few days :)
