### ISSUE TITLE
User cannot be found

### ISSUE THREAD

**Issue by elct9620** [shprink/trendingdevs.com#16]
I already set my location in my profile.
But it could not display me on the list and cannot search me.

First I set the location using "Taoyuan, Taiwan"
So, I guess the parser cannot recognize the "Taoyuan City."
I change it to "Taiwan" and still not show on list after I check it few days.

**Comment by shprink** [comment]
You can use one of the following cities:

![image](https://cloud.githubusercontent.com/assets/1388706/12696699/b616edd8-c736-11e5-8ad7-f895f985f422.png)

with this pattern: `<city>`, `<country>`

If you do so you will be imported next week.

**Comment by elct9620** [comment]
<img width="263" alt="2016-02-08 6 06 10" src="https://cloud.githubusercontent.com/assets/887984/12882749/acb0bb5c-ce8e-11e5-9600-cb330798d306.png">

Hi, I notice the list is update. But I am sure my city is changed to correct value, but I still not shows on the list.

**Comment by shprink** [comment]
You have been added February 3rd. You will be added to this week ranking.
I will push the result tonight

**Comment by benoror** [comment]
Hey @shprink! I also [changed my location](https://github.com/benoror), so hopefully I can be shown in the [trending devs](http://app.trendingdevs.com/explore) too :smile:

**Comment by shprink** [comment]
Cool @benoror! Hector benitez is from your city and also work with toptal, nice guy

**Comment by shprink** [comment]
@elct9620 there you go: http://app.trendingdevs.com/developers/elct9620

**Comment by elct9620** [comment]
Cool! And thanks.
