### ISSUE TITLE
Update data

### ISSUE THREAD

**Issue by montogeek** [shprink/trendingdevs.com#17]
From a Twitter chat I discovered that the data is outdated:
https://twitter.com/mxstbr/status/791267808311177216

It is possible to updated it?

Thanks!

**Comment by shprink** [comment]
Nope. Project is down, you can find similar project out there :)

**Comment by montogeek** [comment]
Any suggestions?

I really like the algorithm :)

**Comment by benoror** [comment]
http://coderstats.net/ ?

**Comment by montogeek** [comment]
Thanks!

**Comment by shprink** [comment]
Check this out: http://github-awards.com/

**Comment by montogeek** [comment]
@shprink Its algorithm is based purely on stars. Yours is better
