### ISSUE TITLE
Issue - Typo 'Result' -> 'result'

### ISSUE THREAD

**Issue by sidthesloth92** [shprink/trendingdevs.com#4]
Typo in search page. It should 'Result' instead it is 'result'. Also 'No users found' would be a better message to display
<img width="291" alt="screen shot 2015-11-13 at 9 52 42 pm" src="https://cloud.githubusercontent.com/assets/4656109/11151045/033bf9dc-8a51-11e5-82d2-a8350b1ea1bf.png">

**Comment by shprink** [comment]
Done
