### ISSUE TITLE
Issue - Search button mis-aligned

### ISSUE THREAD

**Issue by sidthesloth92** [shprink/trendingdevs.com#6]
I'm not sure of this. But is the search button mis-aligned. I have no idea what it is doing so far to the right!!

<img width="1252" alt="screen shot 2015-11-13 at 10 00 40 pm" src="https://cloud.githubusercontent.com/assets/4656109/11151268/25f0f896-8a52-11e5-8d3f-aee29cc804c8.png">

**Comment by shprink** [comment]
it is not a bug, but yes I could put it full width. Do you think it is better?

**Comment by sidthesloth92** [comment]
Yeah man, either horizontally centered or full width would do the job.. :)

**Comment by shprink** [comment]
Now full width.
